apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaks
  labels:
    org.citrusframework.yaks/component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: yaks
  template:
    metadata:
      labels:
        name: yaks
    spec:
      serviceAccountName: yaks
      containers:
        - name: yaks
          image: yaks/yaks:latest
          command:
          - yaks
          - operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "yaks"
