[[cli]]
= Command line interface (yaks)

The YAKS command line interface (yaks) is the main entry point for
installing the operator and for running tests on a Kubernetes cluster.

Releases of the CLI are available on:

- Github Releases: https://github.com/citrusfrmaework/yaks/releases
- Homebrew (Mac and Linux): https://formulae.brew.sh/formula/yaks

[[cli-commands]]
== Available Commands

Some of the most used commands are:

.Useful Commands
|===
|Name |Description |Example

|help
|Obtain the full list of available commands
|`yaks help`

|completion
|Generates completion scripts (bash, zsh)
|`yaks completion`

|install
|Install YAKS operator and setup cluster (roles, CRDs)
|`yaks install`

|list
|List the results of all tests on given namespace
|`yaks list`

|run
|Deploys and executes a test on given namespace
|`yaks run helloworld.feature`

|delete
|Delete tests by name from given namespace
|`yaks delete helloworld.feature`

|report
|Fetch and generate reports from test results
|`yaks report --fetch -o junit`

|upload
|Upload custom artifacts (steps, extensions) to Minio storage
|`yaks upload ./steps/my-custom-steps`

|uninstall
|Remove YAKS (operator, roles, CRDs, ...) from the cluster
|`yaks uninstall`

|version
|Print current YAKS version
|`yaks version`

|===

The list above is not the full list of available commands. You can run `yaks help` to obtain the full list.
Each sub-command also takes `--help` as parameter to output more information on that specific command usage:

.Overall help
[source, shell script]
----
yaks help
----

[source]
----
YAKS is a platform to enable Cloud Native BDD testing on Kubernetes.

Usage:
  yaks [command]

Available Commands:
  completion  Generates completion scripts
  delete      Delete tests
  help        Help about any command
  install     Installs YAKS on a Kubernetes cluster
  list        List tests
  log         Print the logs of given test
  report      Generate test report from last test run
  run         Run tests
  uninstall   Uninstall YAKS from a Kubernetes cluster
  upload      Upload a local test artifact to the cluster
  version     Display version information

Flags:
      --config string      Path to the config file to use for CLI requests
  -h, --help               help for yaks
  -n, --namespace string   Namespace to use for all operations

Use "yaks [command] --help" for more information about a command.
----

.Command help
[source, shell script]
----
yaks run --help
----

[[cli-install]]
== install

The command `install` performs the YAKS installation on a target cluster. The command has two separate install steps:

. Setup cluster resources (CRDs, roles, rolebindings)
. Install YAKS operator to current namespace (or to the provided namespace in settings)

[[cli-list]]
== list

TODO

[[cli-run]]
== run

TODO

[[cli-delete]]
== delete

TODO

[[cli-logs]]
== log

TODO

[[cli-report]]
== report

TODO

[[cli-upload]]
== upload

TODO

[[cli-uninstall]]
== uninstall

TODO

[[cli-version]]
== version

TODO