[[cli]]
= Command line interface (yaks)

The YAKS command line interface (yaks) is the main entry point for
installing the operator and for running tests on a Kubernetes cluster.

Releases of the CLI are available on:

- Github Releases: https://github.com/citrusfrmaework/yaks/releases
- Homebrew (Mac and Linux): https://formulae.brew.sh/formula/yaks

[[cli-commands]]
== Available Commands

Some of the most used commands are:

.Useful Commands
|===
|Name |Description |Example

|help
|Obtain the full list of available commands
|`yaks help`

|completion
|Generates completion scripts (bash, zsh)
|`yaks completion`

|install
|Install YAKS operator and setup cluster (roles, CRDs)
|`yaks install`

|role
|Add roles and role bindings to the YAKS operator in order to manage additional custom resources
|`yaks role --add role-foo.yaml`

|list
|List the results of all tests on given namespace
|`yaks list`

|run
|Deploys and executes a test on given namespace
|`yaks run helloworld.feature`

|delete
|Delete tests by name from given namespace
|`yaks delete helloworld.feature`

|report
|Fetch and generate reports from test results
|`yaks report --fetch -o junit`

|dump
|Dump all YAKS resources in current namespace (operator, tests, jobs, pods, configmaps, ...)
|`yaks dump`

|upload
|Upload custom artifacts (steps, extensions) to Minio storage
|`yaks upload ./steps/my-custom-steps`

|uninstall
|Remove YAKS (operator, roles, CRDs, ...) from the cluster
|`yaks uninstall`

|version
|Print current YAKS version
|`yaks version`

|===

The list above is not the full list of available commands. You can run `yaks help` to obtain the full list.
Each sub-command also takes `--help` as parameter to output more information on that specific command usage:

[[cli-help]]
== help

.Overall help page
[source, shell script]
----
yaks help
----

.Display help page
[source]
----
YAKS is a platform to enable Cloud Native BDD testing on Kubernetes.

Usage:
  yaks [command]

Available Commands:
  completion  Generates completion scripts
  delete      Delete tests
  dump        Dump the state of YAKS resources for a test
  help        Help about any command
  install     Installs YAKS on a Kubernetes cluster
  list        List tests
  log         Print the logs of given test
  report      Generate test report from last test run
  role        Manage YAKS operator roles and role bindings
  run         Run tests
  uninstall   Uninstall YAKS from a Kubernetes cluster
  upload      Upload a local test artifact to the cluster
  version     Display version information

Flags:
      --config string      Path to the config file to use for CLI requests
  -h, --help               help for yaks
  -n, --namespace string   Namespace to use for all operations

Use "yaks [command] --help" for more information about a command.
----

.Command specific help
[source, shell script]
----
yaks [command] --help
----

.Example
[source, shell script]
----
yaks upload --help

Upload a local test artifact to the cluster so that it can be used when running a test.

Usage:
  yaks upload artifact [flags]

Flags:
  -h, --help   help for upload

Global Flags:
      --config string      Path to the config file to use for CLI requests (default "/Users/cdeppisc/Projects/IBMcloud/auth/kubeconfig")
  -n, --namespace string   Namespace to use for all operations
  -v, --verbose            Print details while performing an operation
----

[[cli-install]]
== install

The command `install` performs the YAKS installation on a target cluster. The command has two separate install steps:

. Setup cluster resources (CRDs, roles, rolebindings)
. Install YAKS operator to current namespace (or to the provided namespace in settings)

[[cli-role]]
== role

TODO

[[cli-list]]
== list

TODO

[[cli-run]]
== run

TODO

[[cli-delete]]
== delete

TODO

[[cli-logs]]
== log

TODO

[[cli-report]]
== report

TODO

[[cli-dump]]
== dump

TODO

[[cli-upload]]
== upload

TODO

[[cli-uninstall]]
== uninstall

TODO

[[cli-version]]
== version

TODO
