[[steps-standard]]
== Standard steps

The standard steps in YAKS provide a lot of basic functionality that you can just use in your feature files. The functionality is shipped as
predefined steps that you add to a feature as you write your test.

Most of the standard steps do leverage capabilities of the underlying test framework Citrus such as creating test variables or printing messages
to the log output.

[[steps-variables]]
=== Create variables

Test variables represent the fundamental concept to own test data throughout your test. Once a variable has been created
you can reference its value in many places in YAKS and Citrus. You can add a new identifier as a variable and reference
its value in many places such as message headers, body content, SQL statements and many more.

.@Given("^variable {name} is \"{value}\"$")
[source,gherkin]
----
Given variable orderId is "1001"
----

This will create the variable `orderId` in the current test context. All subsequent steps and operations may reference the variable with the expression `${orderId}`.
Citrus makes sure to replace the variable placeholder with its actual value before sending out messages and before validating incoming messages. As already mentioned
you can use the variable placeholder expression in many places such as message headers and body content:

.Variable placeholder in a Json payload
[source,json]
----
{
  "id": "${orderId}",
  "name": "Watermelon",
  "amount": 10
}
----

You can create multiple variables in one single step using:

.@Given("^variables$")
[source,gherkin]
----
Given variables
  | orderId  | 1001      |
  | name     | Pineapple |
----

[[steps-log]]
=== Log steps

Logging a message to the output can be helpful in terms of debugging and/or to give information about the context of an operation.

YAKS provides following steps to add log output:

.@Then("^(?:log|print) '{text}'$")
[source,gherkin]
----
Then print 'YAKS provides Cloud native BDD testing!'
And log 'YAKS rocks!'
----

The steps are printing log messages to the output using INFO level. The text that is printed supports test variables
and functions. All placeholders will be replaced before logging.

You can also use multiline log messages as shown in the next example.

.@Then("^(?:log|print)$")
[source,gherkin]
----
Given print
"""
Hello users!

YAKS provides Cloud Native BDD testing on Kubernetes!
"""
----

[[steps-sleep]]
=== Sleep

The `sleep` step lets the test run wait for a given amount of time (in milliseconds). During the sleep no action will be performed and the subsequent steps are postponed respectively.

.@Then("^sleep$")
[source,gherkin]
----
Then sleep
----

The above step performs a sleep with the default time of 5000 milliseconds.

You can also give a time in milliseconds to sleep.

.@Then("^sleep {time} ms$")
[source,gherkin]
----
Then sleep 2500 ms
----

The step receives a numeric parameter that represents the amount of time (in milliseconds) to wait.

TIP: The Citrus framework also provides a set of BDD step implementations that you can use in a feature file. Read more about the available steps
(e.g. for connecting with Selenium) in the official https://citrusframework.org/citrus/reference/2.8.0/html/index.html#cucumber[Citrus documentation on BDD testing].
