[[steps-custom]]
== Custom steps

It's often useful to plug some custom steps into the testing environment. Custom steps help keeping the
tests short and self-explanatory and at the same time help teams to add generic assertions that are meaningful in their
environment.

To add custom steps in YAKS, you can look at the example provided in the xref:../../examples/extension[examples/extension] directory.
The example consists of a feature file (xref:../../examples/extension/extension.feature[examples/extension/extension.feature]) using a custom step from a local project
(xref:../../examples/extension/steps[examples/extension/steps]).

To run the example:

[source]
----
yaks test extension.feature -u steps/
----

The `-u` flag stands for "upload". The steps project is built before running the test and the artifacts are uploaded to a
https://github.com/container-tools/snap[Snap] Minio server, in order for the test to retrieve them
when needed. This happens transparently to the user.

The local library can also be uploaded to the Snap Minio server prior to running the test, using the `yaks upload` command.
