#!/bin/bash

#
# Copyright the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

cross_compile () {
	local extension=""
	local working_dir="$1"
	local label="$2"
	local build_dir="$3"
	local goos="$4"
	local goarch="$5"
	local build_flags="$6"

	export GOOS=$goos
	export GOARCH=$goarch
	export CGO_ENABLED=0

  rm -rf ${build_dir}

	if [ "${goos}" == "windows" ]; then
		extension=".exe"
	fi

  echo "Generating ${label}${extension} ..."

	local target_dir=${build_dir}/${label}
	eval go build "$build_flags" -o ${target_dir}/yaks${extension} ${working_dir}/cmd/manager/*.go

	if [ -n "${GPG_PASS:-}" ]; then
	    gpg --output ${target_dir}/yaks${extension}.asc --armor --detach-sig --passphrase ${GPG_PASS} ${target_dir}/yaks${extension}
	fi

  pushd . && cd ${target_dir} && sha512sum -b yaks${extension} > yaks${extension}.sha512 && popd

	cp ${working_dir}/LICENSE ${target_dir}/
	cp ${working_dir}/NOTICE ${target_dir}/

	pushd . && cd ${target_dir} && tar -zcvf ${working_dir}/${label}.tar.gz $(ls -A) && popd

	rm -rf ${build_dir}
}
