#!/bin/bash

#
# Copyright the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

update_olm() {
    local working_dir="$1"
    local version="$2"
    local snapshot_version="$3"
    local olm_catalog=${working_dir}/deploy/olm-catalog
    local file_version=$(echo $version | tr '[:upper:]' '[:lower:]')

    if [[ "$version" == "$snapshot_version" ]]; then
        echo "Using OLM version: $version"
        return
    fi

    for d in $(find ${olm_catalog} -type d -name "*-snapshot*");
    do
      mv ${d} ${olm_catalog}/yaks/${file_version}
    done

    for f in $(find ${olm_catalog}/yaks/${file_version} -type f -name "*-snapshot*");
    do
      sed -i "s/$snapshot_version/$version/g" $f
      mv ${f} ${f//v*-snapshot/v${file_version}}
    done

    # Update package file
    local package_file=${olm_catalog}/yaks/yaks.package.yaml
    sed -i "s/$snapshot_version/$version/g" $package_file
}
