= Manage custom resources

This example shows how to create custom resources as part of the test.
Creating custom resources is a good way to prepare a proper infrastructure of the test.

For instance the test can create a new Knative broker instance or a Strimzi Kafka cluster
prior to using this infrastructure in the very same test.

== Prepare CRDs

Before you can manage custom resources from a test, you need to make sure that the custom resource definition (CRD) is
available on the cluster.

Assume that there is a CRD `foos.yaks.dev`:

.crd-foo.yaml
[source,yaml]
----
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app: "yaks"
  creationTimestamp: null
  name: foos.yaks.dev
spec:
  group: yaks.dev
  names:
    kind: Foo
    listKind: FooList
    plural: foos
    singular: foo
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: Foo resource schema
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of Test
            properties:
              message:
                type: string
            required:
              - message
            type: object
          status:
            description: Status defines the observed state of Foo
            properties:
              conditions:
                items:
                  description: Condition describes the state of a resource at a certain point.
                  properties:
                    message:
                      description: A human readable message indicating details about the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition.
                      type: string
                  required:
                    - status
                    - type
                  type: object
                type: array
              version:
                type: string
            type: object
        type: object
    subresources:
      status: {}
----

You can create the CRD on the cluster like this:

[source,bash]
----
kubectl apply -f crd-foo.yaml
----

IMPORTANT: You need admin rights on the cluster to install a CRD.

The setup of the CRD is a once-per-cluster task that needs administrative rights on the cluster.
You may need to ask your administrator to create the CRD for you.
You can also use the pre/post script section in YAKS to create the CRD before the test is started.

.yaks-config.yaml
[source,bash]
----
pre:
  - script: apply-crd.sh
post:
  - script: delete-crd.sh
----

The configuration adds pre/post scripts that create/delete the CRD.

.apply-crd.yaml
[source,bash]
----
# create crd
kubectl apply -f crd-foo.yaml
----

.delete-crd.yaml
[source,bash]
----
# delete crd
kubectl delete crd foos.yaks.dev
----

== Prepare role permissions

Prior to using the custom resource in a YAKS test you need to grant role permissions to the YAKS runtime.
Otherwise, the test is not allowed to create the custom resource due to security constraints on the cluster.

The YAKS runtime uses a service account `yaks-viewer` to run the test.
The service account needs to have proper roles and permissions for managing the custom resource.

The YAKS operator uses another service account `yaks-operator`.
This service account needs to have the same permissions on the custom resource, too.
This is because the operator manages the `yaks-viewer` service account in a specific namespace.
When using temporary namespaces as a test runtime the YAKS operator will create the `yaks-viewer` service account and
its roles and permissions on the fly.

IMPORTANT: You should always grant roles and permissions to the `yaks-operator` service account.

The role to manage the new CRD `foos.yaks.dev` would be:

.role-foo.yaml
[source,yaml]
----
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: yaks-operator-foo
  labels:
    app: "yaks"
    yaks.citrusframework.org/append-to-viewer: "true"
rules:
- apiGroups:
    - yaks.dev
  resources:
    - foos
  verbs:
    - create
    - delete
    - get
    - list
    - update
----

The role `yaks-operator-foo` is granted to create/delete/get/list/update custom resources of type `foos.yaks.dev`.

You also need a role binding to the `yaks-operator` service account:

.role-binding-foo.yaml
[source,yaml]
----
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: yaks-operator-foo
  labels:
    app: "yaks"
    yaks.citrusframework.org/append-to-viewer: "true"
subjects:
- kind: ServiceAccount
  name: yaks-operator
roleRef:
  kind: Role
  name: yaks-operator-foo
  apiGroup: rbac.authorization.k8s.io
----

NOTE: You can use the usual Kubernetes tools to create the role and role bindings.
Please make sure to add the role to each operator instance in all namespaces, when using multiple YAKS operators on the cluster.
Also, you may need to use cluster roles when using a global YAKS operator.
All of this is already covered when using the `yaks role` command.

You can use the YAKS command line tool to properly add the role and role binding on the YAKS operator:

[source,bash]
----
yaks role –-add role-foo.yaml
yaks role –-add role-binding-foo.yaml
----

The commands above create the role and role bindings on the `yaks-operator` service account.
The command automatically covers all available operator instances on the cluster.
Also, the command will automatically convert the role to a cluster role when there is a global operator on the cluster.

IMPORTANT: This role setup must be done by a cluster administrator.

Both role resources use a specific label `yaks.citrusframework.org/append-to-viewer: "true"`.
This makes sure that the YAKS operator adds the permissions also to the `yaks-viewer` account.
This is done automatically when the operator starts a new test.

As a naming convention the roles and role bindings targeting on the YAKS operator use the `yaks-operator-` name prefix.

== Write the test

With the preparations described in the previous sections you are ready to use the custom resource in your test.
You can create the custom resource from YAML specification like this:

.custom_resource.feature
[source,gherkin]
----
Scenario: Create foo
  Given create Kubernetes custom resource in foos.yaks.dev
  """
  apiVersion: yaks.dev/v1alpha1
  kind: Foo
  metadata:
    name: inline-foo
  status:
    conditions:
    - type: Ready
      status: true
  """
----

The step above create the custom resource in the current test namespace.
The YAKS operator has applied the proper roles and permissions to the `yaks-viewer` service account.
So you may not run into permission errors when creating this custom resource.

== Usage with temporary namespaces

IMPORTANT: When using temporary namespaces in combination with a non-global YAKS operator, you need to add the roles explicitly
in the runtime configuration in `yaks-config.yaml`. This is not required when using a global YAKS operator.

In case you want to make use of temporary namespaces you need to add the roles to the runtime configuration of the test.
This is because the operator for the temporary namespace will not be able to automatically apply the additional operator
roles.

Please add the roles to the `yaks-config.yaml` as follows.

.yaks-config.yaml
[source,yaml]
----
config:
  operator:
    roles:
      - role-foo.yaml
      - role-binding-foo.yaml
  namespace:
    temporary: true
----

This makes sure that the yaks command line tool installs the roles on the temporary namespace before the test is run.

IMPORTANT: The approach requires the YAKS command line tool user to have sufficient permissions to manage roles on the cluster.
